/*
 * generated by Xtext
 */
package org.xtext.ada2005;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AdbUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return null;
	}

}
