/*
 * generated by Xtext
 */
package org.xtext.ada2005.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ada2005.services.AdbGrammarAccess;

public class AdbParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AdbGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_SL_COMMENT", "RULE_WS");
	}
	
	@Override
	protected org.xtext.ada2005.parser.antlr.internal.InternalAdbParser createParser(XtextTokenStream stream) {
		return new org.xtext.ada2005.parser.antlr.internal.InternalAdbParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Compilation";
	}
	
	public AdbGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AdbGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
